### ISSUE TITLE
feature request: root name = package name

### ISSUE THREAD

**Issue by samoht** [aantron/namespaces#1]
What do you think of having a way to set the root name of the namespace hierarchy to be the package name? For instance, I just would like to compiler https://github.com/mirage/ocaml-git/tree/master/lib in the `Git` namespace, without having to update the filesystem organisation (ie. very similar to the `pack: true` option in `oasis`)

**Comment by aantron** [comment]
That could be quite useful for some (many?) projects. Many projects have multiple to-level packages and can't use this, but for those  with only one, perhaps some tag that allows to make a directory into a namespace with a fixed name will work? Like `"lib": namespace(Git)` instead of just `namespace`?

**Comment by samoht** [comment]
`"lib": namespace(Git)` sounds like a good solution!

**Comment by aantron** [comment]
I called the tag `namespace_with_name(...)`, only because Ocamlbuild emits warnings if you have both a parametric and a nullary tag with the same name. Let me know if you can think of something less ugly :)

See the [`_tags`](https://github.com/aantron/namespaces/blob/master/test/5-rename/_tags) file of the corresponding [test](https://github.com/aantron/namespaces/tree/master/test/5-rename) for usage. The targets to build in that example are `library.cma` and `library.cmxa`.

I don't think this is ready for use in ocaml-git yet, however. Namespaces already supports logically nested libraries with weak dependency edges, i.e. you could have namespace `Git` and module `Git.Unix` living in different Findlib packages `git` and `git.unix`, such that depending on `git` allows you to use and link with `Git`, without pulling in `Git.Unix` or causing a linking error. However, I need to test this more, improve the library file naming, and deal with a few other issues.

Ultimately, I think it will be possible to take a logically-organized source tree, cut it up into libraries using the `namespace_lib` tag, package each one separately for Findlib, and still have nice `ocamldoc`-friendly `.mli` files for documenting the whole project – Namespaces is almost there. I think this is what ocaml-git would want.
